// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Z_4gIwulI_euX9DJyZFeZl8KaxPXnfE',
    appId: '1:571140683342:web:060d1af484983bb1cef51f',
    messagingSenderId: '571140683342',
    projectId: 'mychatapp-6e53a',
    authDomain: 'mychatapp-6e53a.firebaseapp.com',
    storageBucket: 'mychatapp-6e53a.appspot.com',
    measurementId: 'G-EYSRKRGZJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ddxfqrZrBwWzBLGZL0kBREIzrZhAAIk',
    appId: '1:571140683342:android:61a71e2f0900d242cef51f',
    messagingSenderId: '571140683342',
    projectId: 'mychatapp-6e53a',
    storageBucket: 'mychatapp-6e53a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZWQ_NgN7n9YJxvkUP_9H1zPCtwpjA1Og',
    appId: '1:571140683342:ios:658d4291947f55decef51f',
    messagingSenderId: '571140683342',
    projectId: 'mychatapp-6e53a',
    storageBucket: 'mychatapp-6e53a.appspot.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZWQ_NgN7n9YJxvkUP_9H1zPCtwpjA1Og',
    appId: '1:571140683342:ios:710173d3b4c726cfcef51f',
    messagingSenderId: '571140683342',
    projectId: 'mychatapp-6e53a',
    storageBucket: 'mychatapp-6e53a.appspot.com',
    iosBundleId: 'com.example.mychatapp.RunnerTests',
  );
}
